id: P0F6673FA
initial_creation_type: ocr
source_metadata:
  volumes:
    48d669c929404ebc84892c162b9e8270:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: བཅོམ་ལྡན་འདས་ལ་བསྟོད་པ་དཔལ་རྡོ་རྗེ་འཛིན་གྱི་དབྱངས།
      total_pages: 1539
      volume_number: 1
